import type { DataGridThemeProp } from '@affino/datagrid-vue-app'

export const workspaceDataGridTheme: DataGridThemeProp = {
  tokens: {
    gridFontFamily: 'var(--font-sans)',
    gridFontSize: '13px',
    gridTextColor: 'var(--color-text-body)',
    gridBackgroundColor: 'var(--color-surface)',
    gridTextPrimary: 'var(--color-text-strong)',
    gridTextMuted: 'var(--color-text-muted)',
    gridTextSoft: 'var(--color-text-soft)',
    gridGlassBorder: 'var(--color-border)',
    gridAccentStrong: 'var(--color-accent)',
    headerBackgroundColor: 'var(--color-surface-muted)',
    headerTextColor: '#31443a',
    headerBorderColor: 'var(--color-border)',
    headerHighlightBorderColor: 'var(--color-accent)',
    headerHighlightTextColor: 'var(--color-accent)',
    headerSelectedTextColor: 'var(--color-accent)',
    headerSystemTextColor: '#708074',
    bodyRowBackgroundColor: 'var(--color-surface)',
    bodyRowTextColor: 'var(--color-text-body)',
    bodyRowHoverBackgroundColor: '#f7faf8',
    bodyRowSelectedBackgroundColor: 'var(--color-accent-soft)',
    bodyRowSelectedTextColor: 'var(--color-text-strong)',
    bodyCellPaddingX: '12px',
    bodyCellPaddingY: '10px',
    bodyCellBorderColor: '#e3e8e4',
    selectionCellBackgroundColor: 'var(--color-accent-soft)',
    selectionCellTextColor: 'var(--color-text-strong)',
    indexCellBackgroundColor: 'var(--color-surface-subtle)',
    indexCellTextColor: 'var(--color-text-soft)',
    rowDividerSize: '1px',
    rowDividerColor: '#e3e8e4',
    columnDividerSize: '1px',
    columnDividerColor: '#edf0ee',
    headerDividerSize: '1px',
    headerDividerColor: 'var(--color-border)',
    pinnedBackgroundColor: 'var(--color-surface)',
    pinnedLeftBackgroundColor: 'var(--color-surface)',
    pinnedRightBackgroundColor: 'var(--color-surface)',
    gridViewportBackground: 'var(--color-surface)',
    gridFocusOutlineColor: 'var(--color-accent)',
    gridHeaderRowBackgroundColor: 'var(--color-surface-muted)',
    gridHeaderCellBackgroundColor: 'var(--color-surface-muted)',
    gridHeaderCellHoverBackgroundColor: '#edf4ef',
    gridHeaderFilterOpenBackgroundColor: 'var(--color-accent-soft)',
    gridRowSelectedStickyBackgroundColor: 'var(--color-accent-soft)',
    gridRowSelectedRangeBackgroundColor: 'rgba(31, 143, 82, 0.08)',
    gridCheckboxAccentColor: 'var(--color-accent)',
    gridSortIndicatorColor: 'var(--color-accent)',
    gridHeaderFilterHighlightColor: 'var(--color-accent)',
    gridFilterTriggerBorderColor: 'var(--color-border)',
    gridFilterTriggerBackgroundColor: 'var(--color-surface)',
    gridFilterTriggerHoverBorderColor: 'var(--color-accent)',
    gridFilterTriggerHoverTextColor: 'var(--color-accent)',
    gridFilterTriggerActiveBorderColor: 'var(--color-accent)',
    gridFilterTriggerActiveBackgroundColor: 'var(--color-accent-soft)',
    gridFilterTriggerActiveTextColor: 'var(--color-accent)',
    gridResizeHandleHoverColor: 'var(--color-accent)',
    gridNumericTextColor: 'var(--color-text-body)',
    gridEditableHoverBackgroundColor: '#f7faf8',
    gridSelectionRangeBackgroundColor: 'rgba(31, 143, 82, 0.06)',
    gridSelectionCopiedBorderColor: 'var(--color-accent)',
    gridSelectionCopiedBackgroundColor: 'rgba(31, 143, 82, 0.08)',
    gridSelectionFillPreviewBackgroundColor: 'rgba(31, 143, 82, 0.12)',
    gridSelectionMovePreviewBackgroundColor: 'rgba(34, 49, 38, 0.08)',
    gridSelectionAnchorBackgroundColor: 'var(--color-accent)',
    gridSelectionActiveBorderColor: 'var(--color-accent)',
    gridEditorBorderColor: 'var(--color-accent)',
    gridEditorBackgroundColor: 'var(--color-surface)',
    gridEditorFocusBorderColor: 'var(--color-accent)',
    gridEditorFocusRingColor: 'rgba(31, 143, 82, 0.16)',
    gridStickyBackgroundColor: 'var(--color-surface)',
    gridStickyShadowColor: 'rgba(21, 34, 25, 0.08)',
    gridStickyRangeBackgroundColor: 'rgba(31, 143, 82, 0.08)',
    gridStickyRangeBorderColor: 'var(--color-accent)',
    gridStickyAnchorBackgroundColor: 'var(--color-accent)',
    gridStickyAnchorBorderColor: 'var(--color-accent)',
    gridStickyActiveBorderColor: 'var(--color-accent)',
    gridHeaderStickyBackgroundColor: 'var(--color-surface-muted)',
    gridSelectionOverlayBorderColor: 'var(--color-accent)',
    gridSelectionOverlayBackgroundColor: 'rgba(31, 143, 82, 0.05)',
    gridSelectionOverlayFillBorderColor: 'var(--color-accent)',
    gridSelectionOverlayFillBackgroundColor: 'rgba(31, 143, 82, 0.1)',
    gridSelectionOverlayMoveBorderColor: 'var(--color-text-body)',
    gridSelectionOverlayMoveBackgroundColor: 'rgba(34, 49, 38, 0.08)',
    gridSelectionHandleBorderColor: 'var(--color-accent-contrast)',
    gridSelectionHandleBackgroundColor: 'var(--color-accent)',
    gridMoveHandleHoverBackgroundColor: 'var(--color-accent)',
    gridHintBorderColor: 'var(--color-border)',
    gridHintBackgroundColor: '#f7faf8',
    gridColumnMenuBorderColor: 'var(--color-border)',
    gridColumnMenuBackgroundColor: 'var(--color-surface)',
    gridColumnMenuShadowColor: 'rgba(21, 34, 25, 0.12)',
    gridColumnMenuItemHoverBackgroundColor: 'var(--color-surface-muted)',
    gridColumnMenuMutedTextColor: '#708074',
    gridColumnMenuFocusRingColor: 'rgba(31, 143, 82, 0.16)',
    gridColumnMenuSearchBorderColor: 'var(--color-border)',
    gridColumnMenuSearchBackgroundColor: '#f8faf9',
  },
}
